# Generated by Django 5.0.6 on 2024-06-05 13:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_alter_librarybookdetail_description_studentsetails'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentSetails',
            new_name='StudentDetails',
        ),
    ]
