# Generated by Django 5.0.6 on 2024-06-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0003_rename_studentsetails_studentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
