# Generated by Django 5.0.3 on 2024-06-11 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0006_acceptedbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceptedbook',
            name='book',
        ),
        migrations.RemoveField(
            model_name='acceptedbook',
            name='user',
        ),
        migrations.AddField(
            model_name='acceptedbook',
            name='details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='libraryapp.bookrequest'),
            preserve_default=False,
        ),
    ]
