# Generated by Django 5.0.3 on 2024-06-12 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0007_remove_acceptedbook_book_remove_acceptedbook_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedbook',
            name='author',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acceptedbook',
            name='book_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acceptedbook',
            name='details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.studentdetails'),
        ),
    ]
